# -*- coding: utf-8 -*-
"""data_convert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8GvaVprnYiYK6ExbMTRhfUEbTjuTT1R
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

from data_loader_functions import Language, load_data, get_languages, get_cell, get_optimizer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Define constants for special tokens
SOS_token = 0
EOS_token = 1

def indexes_from_word(lang: Language, word: str):
    return [lang.char2index[char] for char in word]

def tensor_from_word(lang: Language, word: str):
    indexes = indexes_from_word(lang, word)
    indexes.append(EOS_token)
    return torch.tensor(indexes, dtype=torch.long, device=device).view(-1, 1)

def tensors_from_pair(input_lang: Language, output_lang: Language, pair: list[str]):
    input_tensor = tensor_from_word(input_lang, pair[0])
    target_tensor = tensor_from_word(output_lang, pair[1])
    return input_tensor, target_tensor